# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de3c62899eef0817d9b37bb821a6401a0cf102f0055a999e162af694d2956472e709effcc495a900b25fdc0cfcee10fcbef9e6d67d4750f1b5d4ffbe59ad42fd

test:
  secret_key_base: 574487484a593acecbec0e042e1ae252f6e1a8d8c758a770fd6f5ab80534ce22a977a370005d4f10a5b8c3b1f473c0494570743e4cb2079a21e948deae026e9c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
